@startuml

title __SUDOKUBOARD's Class Diagram__\n

  namespace com.zvibadash.sudosolve {
    namespace sudokuboard {
      class com.zvibadash.sudosolve.sudokuboard.SudokuBoardEditor {
          ~ btnErase : Button
          ~ btnMagic : Button
          ~ digitControls : Button[]
          ~ isSolve : Boolean
          ~ solved : int[][]
          + SudokuBoardEditor()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace sudokuboard {
      class com.zvibadash.sudosolve.sudokuboard.SudokuBoardView {
          + selectedColumn : int
          + selectedRow : int
          - board : SudokuDigit[][]
          - cellSize : int
          - errorColor : int
          - filledColor : int
          - height : int
          - highlightedColor : int
          - highlightedPaint : Paint
          - hintColor : int
          - isEditable : boolean
          - lessHighlightedColor : int
          - letterPaint : Paint
          - lineColor : int
          - linePaint : Paint
          - width : int
          + SudokuBoardView()
          + clearDigitInSelected()
          + onTouchEvent()
          + setDigitInSelected()
          + unselect()
          # onDraw()
          # onSizeChanged()
          - drawGrid()
          - drawNumbers()
          - drawSelected()
          - getColorFromType()
          - highlightCell()
          - init()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace sudokuboard {
      class com.zvibadash.sudosolve.sudokuboard.SudokuDigit {
          - digit : int
          + SudokuDigit()
          + getDigit()
          + getType()
          + setDigit()
          + setType()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace sudokuboard {
      enum SudokuDigitType {
        EMPTY
        ERROR
        FILLED
        HINTED
      }
    }
  }
  

  com.zvibadash.sudosolve.sudokuboard.SudokuBoardEditor o-- com.zvibadash.sudosolve.sudokuboard.SudokuBoardView : sbv
  com.zvibadash.sudosolve.sudokuboard.SudokuBoardView -up-|> android.view.View
  com.zvibadash.sudosolve.sudokuboard.SudokuDigit o-- com.zvibadash.sudosolve.sudokuboard.SudokuDigitType : type


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
