@startuml

title __ACTIVITIES's Class Diagram__\n

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.CameraModeActivity {
          {static} ~ DATE_PATTERN : String
          {static} ~ FINAL_IMAGE_PREFIX : String
          {static} ~ IMG_SUFFIX : String
          {static} ~ QUALITY : int
          {static} ~ RAW_IMAGE_PREFIX : String
          {static} ~ REQUEST_IMAGE_CAPTURE : int
          {static} ~ TXT_SUFFIX : String
          ~ currentPhotoPath : String
          # onActivityResult()
          # onCreate()
          - createImageFile()
          - createTextB64File()
          - dispatchTakePictureIntent()
          - getBase64FromImage()
          - setImageFromPath()
          - toGrayscale()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.HelpActivity {
          # onCreate()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.HomeActivity {
          # onCreate()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.LoginActivity {
          ~ NO_ERROR : int
          {static} ~ TAG : String
          ~ USERNAME_ERROR : int
          ~ db : SQLiteDatabase
          # onCreate()
          - isValidUsername()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.LoginMenuTemplateActivity {
          + onCreateOptionsMenu()
          + onOptionsItemSelected()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.MainMenuTemplateActivity {
          + onCreateOptionsMenu()
          + onOptionsItemSelected()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.RegisterActivity {
          ~ ALPHANUMERIC_ERROR : int
          ~ ALREADY_EXISTS_ERROR : int
          ~ LENGTH_ERROR : int
          ~ NO_ERROR : int
          {static} ~ TAG : String
          ~ db : SQLiteDatabase
          # onCreate()
          - isValidUsername()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.SettingsActivity {
          # onCreate()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.TestingSessionsActivity {
          ~ btSaveSessionContent : Button
          ~ etSessionContent : EditText
          ~ tvUserPrompt : TextView
          # onCreate()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.TestingSudokuBoardViewActivity {
          # onCreate()
      }
    }
  }
  

  namespace com.zvibadash.sudosolve {
    namespace activities {
      class com.zvibadash.sudosolve.activities.WelcomeActivity {
          ~ cdt : CountDownTimer
          # onCreate()
      }
    }
  }
  

  com.zvibadash.sudosolve.activities.CameraModeActivity -up-|> com.zvibadash.sudosolve.activities.MainMenuTemplateActivity
  com.zvibadash.sudosolve.activities.HelpActivity -up-|> com.zvibadash.sudosolve.activities.MainMenuTemplateActivity
  com.zvibadash.sudosolve.activities.HomeActivity -up-|> com.zvibadash.sudosolve.activities.MainMenuTemplateActivity
  com.zvibadash.sudosolve.activities.LoginActivity -up-|> com.zvibadash.sudosolve.activities.LoginMenuTemplateActivity
  com.zvibadash.sudosolve.activities.LoginActivity o-- com.zvibadash.sudosolve.database.SSDBHelper : dbHelper
  com.zvibadash.sudosolve.activities.LoginMenuTemplateActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.zvibadash.sudosolve.activities.MainMenuTemplateActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.zvibadash.sudosolve.activities.RegisterActivity -up-|> com.zvibadash.sudosolve.activities.LoginMenuTemplateActivity
  com.zvibadash.sudosolve.activities.RegisterActivity o-- com.zvibadash.sudosolve.database.SSDBHelper : dbHelper
  com.zvibadash.sudosolve.activities.SettingsActivity -up-|> com.zvibadash.sudosolve.activities.MainMenuTemplateActivity
  com.zvibadash.sudosolve.activities.TestingSessionsActivity -up-|> com.zvibadash.sudosolve.activities.MainMenuTemplateActivity
  com.zvibadash.sudosolve.activities.TestingSudokuBoardViewActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.zvibadash.sudosolve.activities.WelcomeActivity -up-|> androidx.appcompat.app.AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
